In [1]:
import pymysql
import tensorflow as tf
import numpy as np
from PIL import Image
import pandas as pd

2025-04-09 13:52:48.182056: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-09 13:52:48.401585: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1744186968.505685    5798 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744186968.533731    5798 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-09 13:52:48.736600: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

## Database Connection

In [2]:
connection = pymysql.connect(
    host='localhost',
    user='Jack',
    password='53787',
    database='calorie_project'
)

In [36]:
cursor=connection.cursor()

In [81]:
connection.close()

## Model Prediction

In [34]:
model_path="/home/jackson-divakar/Documents/Calorie_Project/Model/best_model.keras"

In [14]:
model=tf.keras.models.load_model(model_path)

In [15]:
image_path="/home/jackson-divakar/Downloads/french_fries.jpg"

In [16]:
def preprocess_image(image_path):
    """Preprocesses the image: loads, resizes, normalizes, and adds batch dimension."""
    image = Image.open(image_path).resize((512, 512))  # Resize to 512x512
    image = np.array(image).astype(np.float32) / 255.0  # Normalize to [0, 1]
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    return image

In [25]:
def predict_labels(image_path):
    labels = {
        'apple_pie': 0, 'cheesecake': 1, 'chicken_curry': 2, 'french_fries': 3,
        'fried_rice': 4, 'hamburger': 5, 'hot_dog': 6, 'ice_cream': 7,
        'omelette': 8, 'pizza': 9, 'sushi': 10
    }
    image_arr=preprocess_image(image_path)
    inv_labels={v:k for k,v in labels.items()}
    model_output=model.predict(image_arr)
    return inv_labels[np.argmax(model_output)]

In [27]:
predict_labels(image_path)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step

'french_fries'

## Calorific values and details

In [84]:
nutrition_data="select * from nutrients_data"

In [85]:
food_nutrition="select * from food_nutrients"

In [86]:
nutrition_data=pd.read_sql(nutrition_data,connection)

/tmp/ipykernel_7223/1876541116.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  nutrition_data=pd.read_sql(nutrition_data,connection)

In [87]:
food_nutrition=pd.read_sql(food_nutrition,connection)

/tmp/ipykernel_7223/978375393.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  food_nutrition=pd.read_sql(food_nutrition,connection)

In [88]:
food_nutrition

        Food Item  Calories (kcal)  Carbs (g)  Protein (g)  Fat (g)
0       apple_pie              300         45            3       13
1      cheesecake              400         35            7       25
2   chicken_curry              500         50           25       20
3    french_fries              300         40            3       15
4      fried_rice              200         35            5        5
5       hamburger              600         50           30       30
6         hot_dog              250         25           10       15
7       ice_cream              200         25            3       10
8        omelette              240          2           18       17
9           pizza              300         35           12       12
10          sushi              200         35            8        3

In [89]:
nutrition_data

,age_group,age_min,age_max,calories_min,calories_max,carbs_min,carbs_max,protein_min,protein_max,fat_min,fat_max,gender
0,Children,2,3,1000,1400,113,228,25,122,22,54,Male
1,Children,2,3,1000,1400,113,228,25,122,22,54,Female
2,Children (Boys),4,8,1200,1800,169,244,38,131,33,58,Male
3,Children (Girls),4,8,1200,1600,169,244,38,131,33,58,Female
4,Children (Boys),9,13,1600,2200,203,293,45,158,40,70,Male
5,Children (Girls),9,13,1400,2000,203,293,45,158,40,70,Female
6,Teen Boys,14,18,2000,2800,270,390,60,210,53,93,Male
7,Teen Girls,14,18,1800,2200,225,325,50,175,44,78,Female
8,Men,19,30,2400,3000,304,439,68,236,60,105,Male
9,Men,31,50,2200,2800,281,406,63,219,56,97,Male
10,Men,51,64,2000,2600,259,374,58,201,51,89,Male
11,Women,19,30,1800,2400,236,341,53,184,47,82,Female
12,Women,31,50,1800,2200,225,325,50,175,44,78,Female
13,Women,51,64,1600,2000,203,293,45,158,40,70,Female
14,Elderly Men,65,100,1800,2400,236,341,53,184,47,82,Male
15,Elderly Women,65,100,1400,2000,191,276,43,149,38,66,Female

 ## Basic Logic

## Necessary Nutrients

In [92]:
total_calories=0
total_protein=0
total_carbs=0
total_fat=0

In [93]:
age=int(input())

 65

In [95]:
gender=input()

 Male

In [96]:
selected_row=nutrition_data[ (nutrition_data['gender']==gender) &  (nutrition_data['age_min'] <=age) & (nutrition_data['age_max'] >=age) ]

In [97]:
required_calories=int(selected_row.loc[:,required_columns[0]])
required_protein=int(selected_row.loc[:,required_columns[1]])
required_carbs=int(selected_row.loc[:,required_columns[2]])
required_fat=int(selected_row.loc[:,required_columns[3]])

/tmp/ipykernel_7223/2285202029.py:1: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  required_calories=int(selected_row.loc[:,required_columns[0]])
/tmp/ipykernel_7223/2285202029.py:2: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  required_protein=int(selected_row.loc[:,required_columns[1]])
/tmp/ipykernel_7223/2285202029.py:3: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  required_carbs=int(selected_row.loc[:,required_columns[2]])
/tmp/ipykernel_7223/2285202029.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  required_fat=int(selected_row.loc[:,required_columns[3]])

## Food Nutrients

In [25]:
item='french_fries' # model prediction
query="select * from food_nutrients where Food = '{}' ".format(item)
cursor.execute(query)
_,food_calories,food_carbs,food_protein,food_fat=cursor.fetchone()
user_id=3 # getting the user_id by log in or sign up
query_2="select * from user_nutrition where user_id ={}".format(user_id)
cursor.execute(query_2)
_,user_calories,user_carbs,user_protein,user_fat=cursor.fetchone()
user_calories-=food_calories
user_carbs-=food_carbs
user_protein-=food_protein
user_fat-=food_fat

## Some Calculation

In [112]:
total_calories+=calories
total_protein+=carbs
total_carbs+=protein
total_fat+=fat

In [113]:
required_calories=required_calories-total_calories
required_protein=required_protein-total_protein
required_carbs=required_carbs-total_carbs
required_fat=required_fat-total_fat

## Log in mechanism

In [194]:

while True:
    user_name=input("Enter the user_name : ")
    user_password=input("Enter your password : ")
    
    
    no_row=cursor.execute("select * from user_data where user_name= '{}' and password_= '{}' ".format(user_name,user_password))
    if no_row==0:
        print("Username and password are not matched")
        user_ans=input('Do u want to sign up [y/n] ?')
        if(user_ans=='y'):
            try:
                user_name=input("Enter the user_name : ")
                user_password=input("Enter your password : ")
                gender="Male" if input("Enter your gender [M/F]: ") == "M" else "Female"
                age=int(input("Enter your age : "))
                cursor.execute("Insert into user_data (user_name,password_,gender,age) values ('{}','{}','{}',{})".format(user_name,user_password,gender,age))

                cursor.execute("select user_id,age,gender from user_data where user_name= '{}' and password_= '{}' ".format(user_name,user_password))
                user_id,age,gender=cursor.fetchone()
                query="select calories_min,carbs_min,protein_min,fat_min from nutrients_data where age_min<={} and age_max>={} and gender='{}'".format(age,age,gender)
                cursor.execute(query)
                required_calories,required_carbs,required_protein,required_fat=cursor.fetchone()
                print(required_calories)
                query_2="insert into user_nutrition (user_id,required_calories,required_carbs,required_protein,required_fat) values ({},{},{},{},{})".format(user_id,required_calories,required_carbs,required_protein,required_fat)
                cursor.execute(query_2)
                connection.commit()
                print("Entry Created")
                break
            except Exception:
                print("Problem creating the entry")
                
        else:
            print("Retry entering the credentials")
    else:
        pass
        "upload ,prediction and calculation process"

Enter the user_name :  J
Enter your password :  1

Username and password are not matched

Do u want to sign up [y/n] ? Y

Retry entering the credentials

Enter the user_name :  jk
Enter your password :  kj

Username and password are not matched

Do u want to sign up [y/n] ? Y

Retry entering the credentials

Enter the user_name :  jhk
Enter your password :  nk

Username and password are not matched

Do u want to sign up [y/n] ? y
Enter the user_name :  Jackson
Enter your password :  123456
Enter your gender [M/F]:  M
Enter your age :  20

2400
Entry Created